# Generated by Django 4.1.2 on 2022-12-19 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePost4th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr2_4th', models.SmallIntegerField(default=0)),
                ('cpar_4th', models.SmallIntegerField(default=0)),
                ('pe_4th', models.SmallIntegerField(default=0)),
                ('spec_4th', models.SmallIntegerField(default=0)),
                ('ucsp_4th', models.SmallIntegerField(default=0)),
                ('philo_4th', models.SmallIntegerField(default=0)),
                ('eapp_4th', models.SmallIntegerField(default=0)),
                ('lrn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePost4th', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradePost3rd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr2_3rd', models.SmallIntegerField(default=0)),
                ('cpar_3rd', models.SmallIntegerField(default=0)),
                ('pe_3rd', models.SmallIntegerField(default=0)),
                ('spec_3rd', models.SmallIntegerField(default=0)),
                ('ucsp_3rd', models.SmallIntegerField(default=0)),
                ('philo_3rd', models.SmallIntegerField(default=0)),
                ('eapp_3rd', models.SmallIntegerField(default=0)),
                ('lrn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePost3rd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradePost2nd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr2_2nd', models.SmallIntegerField(default=0)),
                ('cpar_2nd', models.SmallIntegerField(default=0)),
                ('pe_2nd', models.SmallIntegerField(default=0)),
                ('spec_2nd', models.SmallIntegerField(default=0)),
                ('ucsp_2nd', models.SmallIntegerField(default=0)),
                ('philo_2nd', models.SmallIntegerField(default=0)),
                ('eapp_2nd', models.SmallIntegerField(default=0)),
                ('lrn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePost2nd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr2', models.SmallIntegerField(default=0)),
                ('cpar', models.SmallIntegerField(default=0)),
                ('pe', models.SmallIntegerField(default=0)),
                ('spec', models.SmallIntegerField(default=0)),
                ('ucsp', models.SmallIntegerField(default=0)),
                ('philo', models.SmallIntegerField(default=0)),
                ('eapp', models.SmallIntegerField(default=0)),
                ('lrn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
