# Generated by Django 4.1.2 on 2023-01-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradetest',
            name='SPECC2',
            field=models.SmallIntegerField(default=0),
        ),
    ]
