# Generated by Django 4.1.2 on 2022-12-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradepost',
            name='cpar',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='eapp',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='pe',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='philo',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='pr2',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='gradepost',
            name='ucsp',
        ),
        migrations.AddField(
            model_name='gradepost',
            name='sub',
            field=models.SmallIntegerField(default=1),
        ),
    ]
