# Generated by Django 4.1.2 on 2022-12-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0002_remove_gradepost_cpar_remove_gradepost_eapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradepost',
            name='sub',
        ),
    ]
