# Generated by Django 4.1.2 on 2023-01-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0002_gradetest_specc2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradetest',
            name='lrn',
            field=models.BigIntegerField(),
        ),
    ]
