# Generated by Django 4.1.2 on 2022-12-24 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_basesubjects_sub1_alter_basesubjects_sub2_and_more'),
        ('Grades', '0003_remove_gradepost_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradepost',
            name='sub1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_sub1', to='subjects.basesubjects'),
        ),
        migrations.AddField(
            model_name='gradepost',
            name='sub2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_sub2', to='subjects.basesubjects'),
        ),
        migrations.AddField(
            model_name='gradepost',
            name='sub3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_sub3', to='subjects.basesubjects'),
        ),
        migrations.AddField(
            model_name='gradepost',
            name='sub4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_sub4', to='subjects.basesubjects'),
        ),
        migrations.AddField(
            model_name='gradepost',
            name='sub5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_sub5', to='subjects.basesubjects'),
        ),
        migrations.AddField(
            model_name='gradepost',
            name='sub6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_sub6', to='subjects.basesubjects'),
        ),
        migrations.AddField(
            model_name='gradepost',
            name='sub7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_sub7', to='subjects.basesubjects'),
        ),
        migrations.AddField(
            model_name='gradepost',
            name='sub8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_sub8', to='subjects.basesubjects'),
        ),
    ]
