# Generated by Django 4.1.2 on 2023-01-22 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Grades', '0003_alter_gradetest_lrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradetest',
            name='lrn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePostTest', to=settings.AUTH_USER_MODEL),
        ),
    ]
