# Generated by Django 4.1.2 on 2023-01-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0004_alter_gradetest_lrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradetest',
            name='lrn',
            field=models.CharField(max_length=15),
        ),
    ]
