# Generated by Django 4.1.2 on 2023-01-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0005_alter_gradetest_lrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradetest',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gradetest',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
