# Generated by Django 4.1.2 on 2022-12-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_delete_basesubjects'),
        ('Grades', '0007_alter_gradepost_grade_sub1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradepost',
            name='sub1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject1', to='subjects.coresubjects'),
        ),
    ]
