# Generated by Django 4.1.2 on 2023-01-04 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_db_students_strand'),
        ('Grades', '0009_alter_gradepost_sub1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradepost',
            name='lrn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePost', to='accounts.db_students'),
        ),
    ]
