# Generated by Django 4.1.2 on 2023-01-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentuser_lrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_students',
            name='lrn',
            field=models.CharField(max_length=255),
        ),
    ]
