# Generated by Django 4.1.2 on 2022-11-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentuser_lrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
