# Generated by Django 4.1.2 on 2022-12-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trackandstrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.trackandstrand'),
        ),
    ]
