# Generated by Django 4.1.2 on 2022-12-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentuser_strand'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsection',
            name='room_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
