# Generated by Django 4.1.2 on 2022-11-26 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentuser_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsection',
            name='section_adviser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacheruser'),
        ),
    ]
