# Generated by Django 4.1.2 on 2022-11-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentsection_section_adviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='contact_num',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
