# Generated by Django 4.1.2 on 2023-01-04 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentsection_room_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_students',
            name='strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.trackandstrand'),
        ),
    ]
