# Generated by Django 4.1.2 on 2022-11-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_studentuser_lrn_alter_teacheruser_contact_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheruser',
            name='section_handle',
            field=models.ManyToManyField(null=True, to='accounts.studentsection'),
        ),
    ]
