# Generated by Django 4.1.2 on 2022-11-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_studentsection_section_adviser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsection',
            name='section_adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacheruser'),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='section_handle',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.studentsection'),
        ),
    ]
