# Generated by Django 4.1.2 on 2022-11-30 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_studentsection_section_adviser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade_Year', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='studentuser',
            name='grade_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentyear'),
        ),
    ]
