# Generated by Django 4.1.2 on 2022-11-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_studentyear_studentuser_grade_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_matter', models.CharField(max_length=50)),
                ('grade_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentyear')),
            ],
        ),
    ]
