# Generated by Django 4.1.2 on 2022-11-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='subject_handle',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.subject'),
        ),
    ]
