# Generated by Django 4.1.2 on 2022-11-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_teacheruser_subject_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheruser',
            name='section_handle',
            field=models.ManyToManyField(blank=True, to='accounts.studentsection'),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='subject_handle',
            field=models.ManyToManyField(blank=True, to='accounts.subject'),
        ),
    ]
