# Generated by Django 4.1.2 on 2022-12-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_matter', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpecializedSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_sub', models.CharField(max_length=255)),
            ],
        ),
    ]
