# Generated by Django 4.1.2 on 2022-12-24 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub1', to='subjects.coresubjects')),
                ('sub2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub2', to='subjects.coresubjects')),
                ('sub3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub3', to='subjects.coresubjects')),
                ('sub4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub4', to='subjects.coresubjects')),
                ('sub5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub5', to='subjects.coresubjects')),
                ('sub6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub6', to='subjects.coresubjects')),
                ('sub7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub7', to='subjects.specializedsubjects')),
                ('sub8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub8', to='subjects.specializedsubjects')),
            ],
        ),
    ]
