# Generated by Django 4.1.2 on 2022-12-24 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('subjects', '0002_basesubjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesubjects',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_section', to='accounts.studentsection'),
        ),
    ]
