# Generated by Django 4.1.2 on 2022-12-24 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_basesubjects_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesubjects',
            name='sub1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub1', to='subjects.coresubjects'),
        ),
        migrations.AlterField(
            model_name='basesubjects',
            name='sub2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub2', to='subjects.coresubjects'),
        ),
        migrations.AlterField(
            model_name='basesubjects',
            name='sub3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub3', to='subjects.coresubjects'),
        ),
        migrations.AlterField(
            model_name='basesubjects',
            name='sub4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub4', to='subjects.coresubjects'),
        ),
        migrations.AlterField(
            model_name='basesubjects',
            name='sub5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub5', to='subjects.coresubjects'),
        ),
        migrations.AlterField(
            model_name='basesubjects',
            name='sub6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub6', to='subjects.coresubjects'),
        ),
        migrations.AlterField(
            model_name='basesubjects',
            name='sub7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub7', to='subjects.specializedsubjects'),
        ),
        migrations.AlterField(
            model_name='basesubjects',
            name='sub8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub8', to='subjects.specializedsubjects'),
        ),
    ]
