# Generated by Django 4.1.2 on 2022-12-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_basesubjects_sub1_alter_basesubjects_sub2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseSubjects',
        ),
    ]
