# Generated by Django 4.1.2 on 2022-11-24 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50, null=True)),
                ('Title', models.CharField(max_length=50)),
                ('Body', models.TextField(null=True)),
                ('Published', models.DateTimeField()),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentsection')),
            ],
        ),
        migrations.CreateModel(
            name='GradePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr2', models.SmallIntegerField(default=0)),
                ('cpar', models.SmallIntegerField(default=0)),
                ('pe', models.SmallIntegerField(default=0)),
                ('spec', models.SmallIntegerField(default=0)),
                ('ucsp', models.SmallIntegerField(default=0)),
                ('philo', models.SmallIntegerField(default=0)),
                ('eapp', models.SmallIntegerField(default=0)),
                ('lrn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
