# Generated by Django 4.1.2 on 2022-11-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Body', models.TextField(null=True)),
                ('Section', models.CharField(choices=[('Microsoft', 'Microsoft'), ('Python', 'Python'), ('Java', 'Java'), ('Oracle', 'Oracle')], max_length=50)),
                ('Published', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LRN', models.TextField()),
                ('Name', models.TextField()),
                ('Age', models.TextField()),
                ('Section', models.TextField()),
                ('Sex', models.TextField(default='Undetermined')),
            ],
        ),
    ]
