# Generated by Django 4.1.2 on 2022-12-14 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_file', models.FileField(max_length=255, upload_to='media/schedules/')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sched_section', to='accounts.studentsection')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50, null=True)),
                ('Title', models.CharField(max_length=50)),
                ('Body', models.TextField(null=True)),
                ('Published', models.DateTimeField()),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentsection')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/modules/module_thumbnails')),
                ('file', models.FileField(upload_to='media/modules/')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade', to='accounts.studentyear')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='accounts.subject')),
            ],
        ),
        migrations.CreateModel(
            name='GradePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr2', models.SmallIntegerField(default=0)),
                ('cpar', models.SmallIntegerField(default=0)),
                ('pe', models.SmallIntegerField(default=0)),
                ('spec', models.SmallIntegerField(default=0)),
                ('ucsp', models.SmallIntegerField(default=0)),
                ('philo', models.SmallIntegerField(default=0)),
                ('eapp', models.SmallIntegerField(default=0)),
                ('pr2_2nd', models.SmallIntegerField(default=0)),
                ('cpar_2nd', models.SmallIntegerField(default=0)),
                ('pe_2nd', models.SmallIntegerField(default=0)),
                ('spec_2nd', models.SmallIntegerField(default=0)),
                ('ucsp_2nd', models.SmallIntegerField(default=0)),
                ('philo_2nd', models.SmallIntegerField(default=0)),
                ('eapp_2nd', models.SmallIntegerField(default=0)),
                ('pr2_3rd', models.SmallIntegerField(default=0)),
                ('cpar_3rd', models.SmallIntegerField(default=0)),
                ('pe_3rd', models.SmallIntegerField(default=0)),
                ('spec_3rd', models.SmallIntegerField(default=0)),
                ('ucsp_3rd', models.SmallIntegerField(default=0)),
                ('philo_3rd', models.SmallIntegerField(default=0)),
                ('eapp_3rd', models.SmallIntegerField(default=0)),
                ('pr2_4th', models.SmallIntegerField(default=0)),
                ('cpar_4th', models.SmallIntegerField(default=0)),
                ('pe_4th', models.SmallIntegerField(default=0)),
                ('spec_4th', models.SmallIntegerField(default=0)),
                ('ucsp_4th', models.SmallIntegerField(default=0)),
                ('philo_4th', models.SmallIntegerField(default=0)),
                ('eapp_4th', models.SmallIntegerField(default=0)),
                ('lrn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
