# Generated by Django 4.1.2 on 2022-11-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Section',
            field=models.CharField(choices=[(1, 'Microsoft'), (2, 'Python'), (3, 'Java'), (4, 'Oracle')], max_length=50),
        ),
    ]
