# Generated by Django 4.1.2 on 2022-10-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Sex',
            field=models.TextField(default='Undetermined'),
        ),
    ]
