# Generated by Django 4.1.2 on 2022-12-14 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('std_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradepost',
            name='lrn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePost', to='accounts.db_students'),
        ),
    ]
