# Generated by Django 4.1.2 on 2022-11-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0002_student_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Body', models.TextField(null=True)),
                ('Section', models.CharField(choices=[('Microsoft', 'Microsoft'), ('Python', 'Python'), ('Java', 'Java'), ('Oracle', 'Oracle')], max_length=50)),
                ('Published', models.DateTimeField()),
            ],
        ),
    ]
