# Generated by Django 4.1.2 on 2022-11-25 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('std_portal', '0002_alter_gradepost_lrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradepost',
            name='lrn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GradePost', to=settings.AUTH_USER_MODEL),
        ),
    ]
