# Generated by Django 4.1.2 on 2022-12-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0003_alter_gradepost_lrn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradePost',
        ),
    ]
