# Generated by Django 4.1.2 on 2022-12-24 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('std_portal', '0004_delete_gradepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studentsection'),
        ),
    ]
