# Generated by Django 4.1.2 on 2022-11-30 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_studentsection_section_adviser_and_more'),
        ('std_portal', '0004_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studentsection'),
        ),
    ]
