# Generated by Django 4.1.2 on 2022-11-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_subject'),
        ('std_portal', '0005_router_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='media')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentyear')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_file', models.FileField(upload_to='media/schedules/<django.db.models.fields.related.ForeignKey>')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentsection')),
            ],
        ),
        migrations.DeleteModel(
            name='Router',
        ),
    ]
