# Generated by Django 4.1.2 on 2022-11-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0006_modules_schedule_delete_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='file',
            field=models.FileField(upload_to='media/modules/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
