# Generated by Django 4.1.2 on 2022-11-30 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_subject'),
        ('std_portal', '0007_alter_modules_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='file',
            field=models.FileField(upload_to='media/modules/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_file',
            field=models.FileField(upload_to='media/schedules/<django.db.models.fields.related.OneToOneField>'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentsection'),
        ),
    ]
