# Generated by Django 4.1.2 on 2022-11-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_subject'),
        ('std_portal', '0008_alter_modules_file_alter_schedule_schedule_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade', to='accounts.studentyear'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='accounts.subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_file',
            field=models.FileField(max_length=255, upload_to='media/schedules/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sched_section', to='accounts.studentsection'),
        ),
    ]
