# Generated by Django 4.1.2 on 2022-11-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0009_alter_modules_grade_alter_modules_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='file',
            field=models.FileField(upload_to='media/modules/'),
        ),
    ]
